export interface Datum {
  Payer: string;
  PayingBank: string;
  Platform: string;
  AccountUsed: string;
  TradeHash: string;
  Seller: string;
  CoinType: string;
  CoinAmount: number;
  NGNPaid: number;
  OpenedAt: string;
  PaidAt: string;
  SpeedSec: number;
}

export const data: Datum[] = [
  {
    Payer: "Alex Johnson",
    PayingBank: "First Bank",
    Platform: "Paxful",
    AccountUsed: "Main Account",
    TradeHash: "#F4240",
    Seller: "Vendor A",
    CoinType: "BTC",
    CoinAmount: 0.05,
    NGNPaid: 4324092,
    OpenedAt: "May 21, 02:47 PM",
    PaidAt: "May 21, 02:48 PM",
    SpeedSec: 30,
  },
  {
    Payer: "Sarah Smith",
    PayingBank: "GTBank",
    Platform: "Noones",
    AccountUsed: "Trading Account",
    TradeHash: "#F47I2",
    Seller: "Vendor B",
    CoinType: "ETH",
    CoinAmount: 0.06,
    NGNPaid: 4224092,
    OpenedAt: "May 21, 01:48 PM",
    PaidAt: "May 21, 01:48 PM",
    SpeedSec: 35,
  },
  {
    Payer: "Mike Brown",
    PayingBank: "Zenith Bank",
    Platform: "Bybit",
    AccountUsed: "Reserved Account",
    TradeHash: "#F48E4",
    Seller: "Vendor c",
    CoinType: "BTC",
    CoinAmount: 0.07,
    NGNPaid: 4124092,
    OpenedAt: "May 21, 12:47 PM",
    PaidAt: "May 21, 12:48 PM",
    SpeedSec: 40,
  },
  {
    Payer: "Alex Johnson",
    PayingBank: "First Bank",
    Platform: "Paxful",
    AccountUsed: "Main Account",
    TradeHash: "#F450B6",
    Seller: "Vendor A",
    CoinType: "ETH",
    CoinAmount: 0.08,
    NGNPaid: 4024092,
    OpenedAt: "May 21, 11:47 AM",
    PaidAt: "May 21, 11:48 AM",
    SpeedSec: 45,
  },
  {
    Payer: "Sarah Smith",
    PayingBank: "GTBank",
    Platform: "Noones",
    AccountUsed: "Trading Account",
    TradeHash: "#F5588",
    Seller: "Vendor B",
    CoinType: "BTC",
    CoinAmount: 0.09,
    NGNPaid: 3924092,
    OpenedAt: "May 21, 10:47 AM",
    PaidAt: "May 21, 10:48 AM",
    SpeedSec: 50,
  },
  {
    Payer: "Mike Brown",
    PayingBank: "Zenith Bank",
    Platform: "Bybit",
    AccountUsed: "Reserved Account",
    TradeHash: "#F5A5A",
    Seller: "Vendor c",
    CoinType: "ETH",
    CoinAmount: 0.1,
    NGNPaid: 3824092,
    OpenedAt: "May 21, 09:47 PM",
    PaidAt: "May 21, 09:48 PM",
    SpeedSec: 55,
  },
  {
    Payer: "Alex Johnson",
    PayingBank: "First Bank",
    Platform: "Paxful",
    AccountUsed: "Main Account",
    TradeHash: "#F5F2C",
    Seller: "Vendor A",
    CoinType: "BTC",
    CoinAmount: 0.11,
    NGNPaid: 3724092,
    OpenedAt: "May 21, 08:47 AM",
    PaidAt: "May 21, 08:48 AM",
    SpeedSec: 60,
  },
  {
    Payer: "Sarah Smith",
    PayingBank: "GTBank",
    Platform: "Noones",
    AccountUsed: "Trading Account",
    TradeHash: "#F63FE",
    Seller: "Vendor B",
    CoinType: "ETH",
    CoinAmount: 0.12,
    NGNPaid: 3624092,
    OpenedAt: "May 21, 07:47 AM",
    PaidAt: "May 21, 07:48 AM",
    SpeedSec: 65,
  },
  {
    Payer: "Mike Brown",
    PayingBank: "Zenith Bank",
    Platform: "Bybit",
    AccountUsed: "Reserved Account",
    TradeHash: "#F5A5A",
    Seller: "Vendor c",
    CoinType: "BTC",
    CoinAmount: 0.1,
    NGNPaid: 3824092,
    OpenedAt: "May 21, 05:47 PM",
    PaidAt: "May 21, 08:48 PM",
    SpeedSec: 70,
  },
  {
    Payer: "Alex Johnson",
    PayingBank: "First Bank",
    Platform: "Paxful",
    AccountUsed: "Main Account",
    TradeHash: "#F6DA2",
    Seller: "Vendor A",
    CoinType: "BTC",
    CoinAmount: 0.14,
    NGNPaid: 3424092,
    OpenedAt: "May 21, 05:47 AM",
    PaidAt: "May 21, 06:48 AM",
    SpeedSec: 75,
  },
];
